# Kerberos configuration for the coact-daemon container.

[libdefaults]
    default_realm = SLAC.STANFORD.EDU
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    forwardable = true
    ticket_lifetime = 90000
    renew_lifetime = 7d
    clockskew = 300

[realms]
    SLAC.STANFORD.EDU = {
        kdc = k5auth1.slac.stanford.edu:88
        kdc = k5auth2.slac.stanford.edu:88
        kdc = k5auth3.slac.stanford.edu:88
        master_kdc = k5auth1.slac.stanford.edu:88
        admin_server = k5admin.slac.stanford.edu
        kpasswd_server = k5passwd.slac.stanford.edu
        default_domain = slac.stanford.edu
    }
    SDF.SLAC.STANFORD.EDU = {
        kdc = sdfkdc001.sdf.slac.stanford.edu:88
        kdc = sdfkdc002.sdf.slac.stanford.edu:88
        master_kdc = sdfkdc001.sdf.slac.stanford.edu:88
        admin_server = sdfkdc001.sdf.slac.stanford.edu:88
        kpasswd_server = sdfkdc001.sdf.slac.stanford.edu:88
        default_domain = sdf.slac.stanford.edu
    }

[domain_realm]
    .slac.stanford.edu = SLAC.STANFORD.EDU
    slac.stanford.edu = SLAC.STANFORD.EDU
    .sdf.slac.stanford.edu = SDF.SLAC.STANFORD.EDU
    sdf.slac.stanford.edu = SDF.SLAC.STANFORD.EDU
