# NSS configuration for the coact-daemon container.

passwd:     files sss
group:      files sss
shadow:     files sss
gshadow:    files

hosts:      files dns myhostname
networks:   files

protocols:  files
services:   files
ethers:     files
rpc:        files

netgroup:   files sss
automount:  files sss
publickey:  files
bootparams: files
aliases:    files
